using NakamaShop.Models;

namespace NakamaShop.Data
{
    public static class DbInitializer
    {
        public static void Seed(IApplicationBuilder applicationBuilder)
        {
            NakamaShopDbContext context = applicationBuilder.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<NakamaShopDbContext>();

            if (!context.Categories.Any())
            {
                context.Categories.AddRange(Categories.Select(c => c.Value));
                context.SaveChanges();
            }

            if (!context.AnimeProducts.Any())
            {
                context.AnimeProducts.AddRange(
                    // FIGURAS
                    new AnimeProduct { Name = "Figura Luffy Gear 5", AnimeSeries = "One Piece", ImageThumbnailUrl = "/Images/Luffy Gear 5.jpg", Price = 89.99m, ShortDescription = "El Dios del Sol Nika", LongDescription = "Esta impresionante figura captura a Monkey D. Luffy en su transformación más poderosa: el Gear 5, la forma del Dios del Sol Nika. Con detalles increíbles en su cabello blanco y su ropa rasgada, esta pieza de colección es perfecta para los fans de One Piece. Fabricada en PVC de alta calidad, mide aproximadamente 25 cm de altura. Incluye efectos de nubes y aura blanca que rodean al personaje. Una obra maestra del anime que no puede faltar en tu colección. Edición limitada con certificado de autenticidad incluido.", InStock = true, IsProductOfTheWeek = true, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Figura Zoro (Santoryu)", AnimeSeries = "One Piece", ImageThumbnailUrl = "/Images/Zoro (Santoryu).jpg", Price = 75.00m, ShortDescription = "Estilo de tres espadas", LongDescription = "Roronoa Zoro en su icónica postura de tres espadas, con Wado Ichimonji, Sandai Kitetsu y Shusui listas para el combate. Esta figura de 22 cm captura perfectamente la determinación del espadachín más poderoso de la tripulación del Sombrero de Paja. Fabricada en PVC premium con pintura detallada a mano, cada cicatriz y músculo está perfectamente representado. La capa verde ondeando al viento añade dinamismo a la pose. Ideal para coleccionistas y fans del anime. Base decorativa incluida con el logo de los Piratas del Sombrero de Paja.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Nendoroid Naruto Uzumaki", AnimeSeries = "Naruto", ImageThumbnailUrl = "/Images/Nendoroid Naruto Uzumaki.jpg", Price = 45.99m, ShortDescription = "Versión Shippuden articulada", LongDescription = "El Nendoroid oficial de Naruto Uzumaki en su versión Shippuden es una figura articulada de estilo chibi que captura toda la energía del ninja más famoso de Konoha. Mide aproximadamente 10 cm y viene con múltiples accesorios intercambiables: tres expresiones faciales distintas, efectos de Rasengan en miniatura y kunais de repuesto. Su diseño tierno y detallado lo hace perfecto tanto para coleccionistas serios como para fans casuales. Fabricado por Good Smile Company con los más altos estándares de calidad japonesa. Incluye base articulada y manual de instrucciones.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Figura Sasuke Uchiha", AnimeSeries = "Naruto", ImageThumbnailUrl = "/Images/Sasuke Uchiha.jpg", Price = 70.00m, ShortDescription = "Con efecto Chidori", LongDescription = "Sasuke Uchiha en su forma más intensa, canalizando el poder del Chidori entre sus dedos. Esta figura de 23 cm captura perfectamente la frialdad y determinación del último sobreviviente del clan Uchiha. El efecto eléctrico azul alrededor de su mano está fabricado en resina translúcida especial que simula el movimiento del rayo. Sus ojos Sharingan están pintados con detalle microscópico. La expresión seria del personaje transmite toda la intensidad de sus batallas épicas. Base decorativa con efectos de electricidad incluida. Perfecta para fans de Naruto Shippuden.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Goku Super Saiyan Blue", AnimeSeries = "Dragon Ball Super", ImageThumbnailUrl = "/Images/Goku Super Saiyan Blue.png", Price = 65.00m, ShortDescription = "Estatua Banpresto 25cm", LongDescription = "Son Goku en su transformación Super Saiyan Blue, la forma que combina el poder del Super Saiyan con el ki divino del dios. Esta estatua oficial de Banpresto mide 25 cm y está fabricada en PVC de alta calidad. El cabello azul celeste con detalles en degradado y el aura de energía que lo rodea están pintados con técnica avanzada. La pose de combate con ki concentrado en las manos transmite toda la potencia del Guerrero del Universo 7. Base decorativa con logo de Dragon Ball Super incluida. Coleccionable oficial con sello de autenticidad.", InStock = true, IsProductOfTheWeek = true, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Vegeta (Orgullo Saiyan)", AnimeSeries = "Dragon Ball Z", ImageThumbnailUrl = "/Images/Vegeta (Orgullo Saiyan).jpg", Price = 62.50m, ShortDescription = "Pose de batalla clásica", LongDescription = "El Príncipe de los Saiyans en su icónica pose de batalla con la armadura azul y dorada característica de Dragon Ball Z. Esta figura de 22 cm captura el orgullo y la arrogancia del guerrero más orgulloso del universo. Fabricada en PVC premium, cada detalle de su armadura está esculpido con precisión milimétrica. El cabello en llamas doradas del Super Saiyan y su mirada desafiante hacen de esta pieza un must-have para cualquier coleccionista de Dragon Ball. Base negra con el logo del Universo 7 incluida. Edición especial conmemorativa.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Eren Yeager (Forma Titán)", AnimeSeries = "Attack on Titan", ImageThumbnailUrl = "/Images/Eren Yeager (Forma Titán).jpg", Price = 95.00m, ShortDescription = "Figura edición limitada", LongDescription = "Eren Yeager en su aterradora Forma Titán, representando uno de los momentos más épicos de Attack on Titan. Esta figura de edición limitada mide 30 cm y captura la transformación del protagonista con un nivel de detalle excepcional. Los músculos expuestos, el vapor emanando de su cuerpo y la expresión feroz están esculpidos con maestría artesanal. Fabricada en resina de alta calidad con pintura aplicada a mano por artistas especializados. Incluye diorama de base con restos de edificios destruidos. Solo 500 unidades disponibles mundialmente. Certificado de autenticidad numerado incluido.", InStock = false, IsProductOfTheWeek = false, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Mikasa Ackerman", AnimeSeries = "Attack on Titan", ImageThumbnailUrl = "/Images/Mikasa Ackerman.jpg", Price = 78.00m, ShortDescription = "Con equipo de maniobras 3D", LongDescription = "Mikasa Ackerman, la guerrera más poderosa de la humanidad, en acción con su equipo de maniobras tridimensionales. Esta figura de 24 cm la muestra en pleno vuelo con sus espadas de acero elevado listas para cortar la nuca de un titán. El cabello negro ondeando al viento y la bufanda roja característica están representados con detalle excepcional. Las alas de libertad bordadas en su capa militar brillan con pintura especial. Fabricada en PVC de alta calidad con base que simula un tejado de Shiganshina. Una pieza imprescindible para fans del anime.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Tanjiro Kamado", AnimeSeries = "Demon Slayer", ImageThumbnailUrl = "/Images/Tanjiro Kamado.jpg", Price = 55.00m, ShortDescription = "Efecto respiración de agua", LongDescription = "Tanjiro Kamado ejecutando la Primera Forma de la Respiración del Agua: Danza de la Superficie del Agua. Esta figura de 22 cm captura el instante exacto del ataque con un efecto de agua translúcida que rodea su katana negra. El kimono a cuadros verde y negro y la cicatriz en la frente están pintados con precisión extraordinaria. La expresión concentrada del cazador de demonios transmite toda la determinación del personaje. Base decorativa que simula agua en movimiento incluida. Fabricada en PVC premium con certificado oficial de Ufotable.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Nezuko en caja", AnimeSeries = "Demon Slayer", ImageThumbnailUrl = "/Images/Nezuko en caja.jpg", Price = 48.00m, ShortDescription = "Versión pequeña adorable", LongDescription = "Nezuko Kamado en su adorable versión pequeña dentro de su icónica caja de madera. Esta figura chibi de 15 cm captura a la demonio más tierna del anime asomando curiosamente desde su escondrijo con su bambú en la boca. El kimono rosa con patrón de cáñamo verde y su cabello negro con horquillas rosadas están detallados con colores vibrantes. Sus enormes ojos rosas expresan toda la ternura del personaje. Perfecta para escritorios y estantes. Fabricada en PVC suave de alta calidad. Incluye caja decorativa desmontable que reproduce fielmente la del anime.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Satoru Gojo (Sin venda)", AnimeSeries = "Jujutsu Kaisen", ImageThumbnailUrl = "/Images/Satoru Gojo (Sin venda).jpg", Price = 110.00m, ShortDescription = "Expansión de dominio: Vacío Infinito", LongDescription = "Satoru Gojo sin su característica venda, mostrando sus míticos ojos azules de seis ojos mientras activa su técnica más poderosa: la Expansión de Dominio Vacío Infinito. Esta figura premium de 28 cm captura el momento exacto con efectos de energía azul y violeta en resina translúcida. El cabello blanco alborotado y su sonrisa confiante están esculpidos con maestría artesanal. Considerado el hechicero más fuerte de la actualidad, esta figura lo representa en todo su esplendor. Base con efectos de dominio expandido incluida. Edición limitada con caja especial coleccionable y certificado numerado.", InStock = true, IsProductOfTheWeek = true, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Sukuna (Trono de huesos)", AnimeSeries = "Jujutsu Kaisen", ImageThumbnailUrl = "/Images/Sukuna (Trono de huesos).jpg", Price = 125.00m, ShortDescription = "Figura de lujo", LongDescription = "Ryomen Sukuna, el Rey de las Maldiciones, sentado en su trono de huesos y cadáveres en una pose de poder absoluto. Esta figura de lujo de 32 cm es la representación más impresionante del antagonista más temido de Jujutsu Kaisen. Sus cuatro brazos, tatuajes rojos y la expresión de desprecio absoluto están esculpidos con un nivel de detalle extraordinario. Fabricada en resina de alta calidad con pintura aplicada a mano por artistas japoneses especializados. El trono decorativo incluye efectos malditos en resina translúcida roja. Pieza central perfecta para cualquier vitrina de coleccionista.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Deku Smash", AnimeSeries = "My Hero Academia", ImageThumbnailUrl = "/Images/Deku Smash.jpg", Price = 52.00m, ShortDescription = "One For All 100%", LongDescription = "Izuku Midoriya, el sucesor del One For All, en su ataque definitivo Detroit Smash al 100% de su poder. Esta figura de 21 cm captura el instante del impacto con efectos de viento y energía verde brillante en resina translúcida. El traje verde deteriorado por el uso del poder y los brazos envueltos en vendas muestran el sacrificio del personaje. La expresión determinada de Deku transmite toda la esencia del héroe más trabajador de UA. Base con efectos de impacto y grietas en el suelo incluida. Fabricada en PVC premium con colores vibrantes y durables.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "Bakugo Katsuki", AnimeSeries = "My Hero Academia", ImageThumbnailUrl = "/Images/Bakugo Katsuki.jpg", Price = 54.00m, ShortDescription = "Efecto explosión", LongDescription = "Katsuki Bakugo en plena acción con sus explosiones características activadas, mostrando toda la agresividad y determinación del futuro Número Uno. Esta figura de 22 cm captura su pose de combate con las palmas abiertas rodeadas de explosiones en resina translúcida naranja y amarilla. El traje de héroe negro con granadas decorativas y su cabello rubio alborotado están detallados con precisión. La expresión feroz con dientes apretados es perfectamente característica del personaje. Base con efectos de explosión incluida. Fabricada en PVC de alta calidad con certificado oficial de la UA High School.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Figuras"] },
                    new AnimeProduct { Name = "L (Death Note)", AnimeSeries = "Death Note", ImageThumbnailUrl = "/Images/L (Death Note).png", Price = 40.00m, ShortDescription = "Sentado con su pastel", LongDescription = "L Lawliet, el detective más brillante del mundo, en su icónica postura: sentado en cuclillas con su pastel de fresas favorito en la mano. Esta figura de 18 cm captura perfectamente los rasgos característicos del personaje: ojeras profundas, cabello negro despeinado, ropa blanca holgada y dedos largos. La expresión analítica y misteriosa del detective transmite toda la inteligencia enigmática del personaje. Fabricada en PVC de alta calidad con pintura cuidadosa en cada detalle. Base con laptop incluida para recrear sus sesiones de investigación. Perfecta para fans del thriller psicológico más famoso del anime.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Figuras"] },

                    // COLECCIONABLES
                    new AnimeProduct { Name = "Gomu Gomu no Mi", AnimeSeries = "One Piece", ImageThumbnailUrl = "/Images/Gomu Gomu no Mi.jpg", Price = 35.00m, ShortDescription = "Réplica escala real", LongDescription = "Réplica oficial a escala real de la legendaria Gomu Gomu no Mi, la Fruta del Diablo que convirtió a Monkey D. Luffy en el hombre de goma más poderoso del mundo. Fabricada en resina de alta calidad con textura rugosa característica de las frutas del diablo. El patrón espiral negro sobre fondo rojo intenso está pintado a mano con colores vibrantes y durables. Mide exactamente igual que la fruta mostrada en el manga y anime. Base de exhibición transparente incluida. Una pieza imprescindible para cualquier fan de One Piece que quiera tener un pedazo de la Gran Ruta en casa.", InStock = true, IsProductOfTheWeek = true, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Ope Ope no Mi", AnimeSeries = "One Piece", ImageThumbnailUrl = "/Images/Ope Ope no Mi.jpg", Price = 35.00m, ShortDescription = "La fruta del Diablo de Law", LongDescription = "Réplica oficial de la Ope Ope no Mi, la Fruta del Diablo más valiosa del mundo que otorgó a Trafalgar D. Water Law sus poderes médico-quirúrgicos. Esta réplica a escala real está fabricada en resina translúcida con detalles en blanco que imitan perfectamente la apariencia de corazón con espirales del anime. El interior iluminado con luz LED azul crea un efecto espectacular en vitrinas oscuras. Base de exhibición con el nombre de la fruta grabado incluida. Perfecta para recrear los momentos más icónicos de la tripulación del Corazón. Una joya para coleccionistas de One Piece.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Kunai de Minato", AnimeSeries = "Naruto", ImageThumbnailUrl = "/Images/Kunai de Minato.jpg", Price = 22.00m, ShortDescription = "Metal pesado, escala 1:1", LongDescription = "Réplica oficial a escala 1:1 del kunai especial de tres puntas de Minato Namikaze, el Cuarto Hokage de Konoha. Fabricado en metal pesado zinc con acabado metálico brillante, este kunai reproduce fielmente el arma que el Relámpago Amarillo usaba para su técnica de Teletransportación del Espacio-Tiempo. Las inscripciones del sello de teletransportación están grabadas con láser en el mango. El lazo decorativo rojo está fabricado en cordón trenzado auténtico. Incluye funda de cuero sintético para exhibición segura. Peso y balance calibrados para una experiencia auténtica. Certificado de coleccionista incluido.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Banda de la Hoja (Tachada)", AnimeSeries = "Naruto", ImageThumbnailUrl = "/Images/Banda de la Hoja (Tachada).jpg", Price = 12.00m, ShortDescription = "Protector de frente de Itachi", LongDescription = "Réplica del icónico protector de frente del pueblo ninja de la Hoja con el símbolo tachado, tal como lo llevaba Itachi Uchiha tras abandonar Konoha. Este coleccionable está fabricado en metal plateado con el símbolo de la Hoja perfectamente tallado y la marca diagonal grabada profunda. La correa ajustable en tela azul marino permite usarlo como accesorio cosplay o exhibirlo como pieza de colección. Mide exactamente igual que el mostrado en el anime. Una pieza que evoca uno de los sacrificios más emotivos de toda la historia de Naruto. Incluye caja de presentación.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Esfera de 4 estrellas", AnimeSeries = "Dragon Ball", ImageThumbnailUrl = "/Images/Esfera de 4 estrellas.jpg", Price = 15.00m, ShortDescription = "Resina transparente", LongDescription = "Réplica oficial de la Esfera del Dragón de 4 estrellas, la bola más especial para Son Goku por pertenecer a su abuelo adoptivo Son Gohan. Fabricada en resina acrílica transparente de alta calidad, las cuatro estrellas rojas en el interior flotan perfectamente centradas. Mide exactamente 7 cm de diámetro, igual que en el anime y manga original de Akira Toriyama. La superficie perfectamente pulida refleja la luz creando destellos espectaculares. Base circular transparente para exhibición incluida. Ideal para coleccionar las siete esferas completas. Un tributo perfecto al legado de Dragon Ball.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Radar del Dragón", AnimeSeries = "Dragon Ball", ImageThumbnailUrl = "/Images/Radar del Dragón.jpg", Price = 28.00m, ShortDescription = "Con luces y sonidos", LongDescription = "Réplica funcional del Radar del Dragón inventado por el genio Bulma Brief para localizar las siete Esferas del Dragón en todo el mundo. Este coleccionable electrónico reproduce fielmente el diseño circular verde con pantalla de radar del anime. Incluye luces LED que imitan el pitido de localización y tres efectos de sonido originales extraídos directamente del anime. La pantalla frontal muestra animación de puntos parpadeantes. Funciona con pilas AAA incluidas. Fabricado en ABS de alta calidad con acabado metálico. El accesorio más nostálgico para cualquier fan que creció viendo las aventuras de Goku.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Llave del Sótano", AnimeSeries = "Attack on Titan", ImageThumbnailUrl = "/Images/Llave del Sótano.jpg", Price = 10.00m, ShortDescription = "El secreto de Grisha Yeager", LongDescription = "Réplica de la icónica llave del sótano de Grisha Yeager, el objeto más misterioso y codiciado de los primeros arcos de Attack on Titan. Esta pequeña pero significativa pieza está fabricada en metal envejecido con acabado oxidado que reproduce el desgaste mostrado en el anime. Eren Yeager llevó esta llave durante años como recuerdo de su padre y promesa de descubrir los secretos del mundo. Mide 6 cm y viene con cordón de cuero para usar como colgante. Incluye pequeña nota con la leyenda del sótano. El regalo perfecto para fans que aprecian los detalles narrativos del anime.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Death Note Real", AnimeSeries = "Death Note", ImageThumbnailUrl = "/Images/Death Note Real.jpg", Price = 20.00m, ShortDescription = "Cuaderno con reglas incluidas", LongDescription = "Réplica oficial del cuaderno de la muerte usado por Light Yagami para convertirse en el dios del nuevo mundo. Este cuaderno de tapa negra dura reproduce fielmente el diseño del anime con el título Death Note grabado en letras doradas en la portada. El interior incluye las 60 reglas oficiales del Death Note impresas en papel envejecido, exactamente como aparecen en el manga. Páginas en blanco de alta calidad para uso personal. Incluye pluma negra especial de regalo. Fabricado en cuero sintético premium. La pieza más icónica de Death Note para fans del thriller psicológico más aclamado del anime.", InStock = true, IsProductOfTheWeek = true, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Dedo de Sukuna", AnimeSeries = "Jujutsu Kaisen", ImageThumbnailUrl = "/Images/Dedo de Sukuna.jpg", Price = 18.00m, ShortDescription = "Réplica de objeto maldito", LongDescription = "Réplica del legendario dedo maldito de Ryomen Sukuna, los veinte fragmentos del cuerpo del Rey de las Maldiciones que desatan poder destructor al ser consumidos. Esta espeluznante réplica está fabricada en resina flexible con textura realista y vendas de tela auténtica que reproducen fielmente el aspecto del anime. El dedo emana una suave luz roja cuando se presiona el centro, simulando la energía maldita contenida. Mide exactamente como se muestra en la serie. Base de exhibición con inscripciones en japonés incluida. La pieza más perturbadora y única para fans de Jujutsu Kaisen.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Katana de Tanjiro", AnimeSeries = "Demon Slayer", ImageThumbnailUrl = "/Images/Katana de Tanjiro.jpg", Price = 120.00m, ShortDescription = "Acero al carbono (ornamental)", LongDescription = "Réplica ornamental de la katana negra de Tanjiro Kamado, la espada que cambió de color a negro al ser empuñada por el cazador de demonios de la Respiración del Agua. Fabricada en acero al carbono de alta calidad con hoja de 68 cm y filo romo para seguridad en exhibición. La guardia circular con patrón floral y el mango envuelto en cordón negro trenzado reproducen fielmente el diseño del anime. La vaina lacada en negro con detalles dorados es una obra de artesanía japonesa. Incluye soporte de madera para exhibición en pared. Certificado de autenticidad del herrero. Solo para mayores de 18 años.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Pendientes Hanafuda", AnimeSeries = "Demon Slayer", ImageThumbnailUrl = "/Images/Pendientes Hanafuda.jpg", Price = 15.00m, ShortDescription = "Legado de la familia Kamado", LongDescription = "Réplica oficial de los icónicos pendientes Hanafuda de la familia Kamado, el símbolo del linaje de cazadores de demonios más antiguo de Japón. Estos pendientes de aro con el diseño de flor del sol están fabricados en plata de ley 925 con acabado mate. El patrón floral está grabado con precisión milimétrica reproduciendo exactamente los pendientes de Tanjiro, su padre y todos sus ancestros. Los aros de cierre seguro garantizan comodidad durante el uso. Incluyen caja de joyería con papel de seda. Perfectos para cosplay o como joya cotidiana para fans de Demon Slayer. Talla única ajustable.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Pokéball Clásica", AnimeSeries = "Pokémon", ImageThumbnailUrl = "/Images/Pokéball Clásica.jpg", Price = 25.00m, ShortDescription = "Apertura por botón", LongDescription = "Réplica oficial a escala real de la icónica Pokéball clásica, el artefacto inventado por el Profesor Oak que revolucionó el mundo de los entrenadores Pokémon. Esta réplica de 7 cm de diámetro se abre pulsando el botón central, revelando un interior iluminado con luz LED blanca que simula la captura de un Pokémon. Fabricada en ABS de alta calidad con acabado brillante rojo y blanco impecable. El botón central tiene mecanismo de click satisfactorio. Incluye base transparente para exhibición. Funciona con pila de botón incluida. El regalo perfecto para fans que crecieron jugando Pokémon Rojo y Azul.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Póster Recompensa Sanji", AnimeSeries = "One Piece", ImageThumbnailUrl = "/Images/Póster Recompensa Sanji.jpg", Price = 8.00m, ShortDescription = "Only Alive version", LongDescription = "Réplica del infame cartel de se busca de Vinsmoke Sanji con el mítico Only Alive, la orden especial que lo distingue del resto de la tripulación del Sombrero de Paja. Este póster de alta resolución impreso en papel envejecido de 30x42 cm reproduce fielmente el diseño mostrado en el anime con la borrosa foto de Sanji. Los bordes desgastados y el efecto amarillento del tiempo están impresos para máximo realismo. Incluye tubo de cartón para envío sin daños y cinta de montaje. Perfecto para decorar habitaciones, estudios o locales. Una pieza humorística e icónica de One Piece.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Sombrero de Chopper", AnimeSeries = "One Piece", ImageThumbnailUrl = "/Images/Sombrero de Chopper.jpg", Price = 25.00m, ShortDescription = "Suave y acolchado", LongDescription = "Réplica del adorable sombrero rosa de Tony Tony Chopper, el médico reno de la tripulación del Sombrero de Paja y uno de los personajes más queridos de One Piece. Este sombrero de peluche suave y acolchado reproduce fielmente el diseño original con la franja rosa característica y el botón dorado frontal. Fabricado en felpa de alta calidad lavable a máquina. Talla única ajustable con elástico interior que se adapta a adultos y niños. Perfecto para cosplay, eventos de anime o simplemente para llevar el espíritu nakama a donde vayas. Incluye bolsa de tela con logo de NakamaShop.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },
                    new AnimeProduct { Name = "Máscara de Ken Kaneki", AnimeSeries = "Tokyo Ghoul", ImageThumbnailUrl = "/Images/Máscara de Ken Kaneki.jpg", Price = 30.00m, ShortDescription = "Cuero sintético ajustable", LongDescription = "Réplica oficial de la icónica máscara de ghoul de Ken Kaneki, creada por el fabricante de máscaras Uta para el protagonista de Tokyo Ghoul. Fabricada en cuero sintético premium de color negro con los detalles blancos del diseño de boca con dientes y los remaches metálicos perfectamente reproducidos. El sistema de sujeción ajustable con correas de cuero garantiza comodidad durante horas. Talla única que se adapta a diferentes tamaños de cabeza. Perfecta para cosplay de alta calidad o exhibición en vitrina. Incluye caja de presentación con diseño temático de Tokyo Ghoul. Una pieza oscura e impresionante para fans del anime.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Coleccionables"] },

                    // MANGA
                    new AnimeProduct { Name = "One Piece Vol. 100", AnimeSeries = "One Piece", ImageThumbnailUrl = "/Images/One Piece Vol. 100.jpg", Price = 9.99m, ShortDescription = "Edición conmemorativa", LongDescription = "El volumen 100 de One Piece es un hito histórico en el mundo del manga, celebrando más de 25 años de la obra maestra de Eiichiro Oda. Esta edición conmemorativa especial incluye portada holográfica con todos los personajes principales de la saga, páginas a color exclusivas de momentos icónicos y comentarios del propio Oda sobre su viaje creativo. El volumen narra los eventos cruciales de Wano con la batalla épica en la cima de Onigashima. Papel de alta calidad con impresión HD que resalta los detalles del arte de Oda. Incluye marcapáginas coleccionable y póster desplegable. El tomo más especial de la colección.", InStock = true, IsProductOfTheWeek = true, Category = Categories["Manga"] },
                    new AnimeProduct { Name = "Naruto Gold Vol. 1", AnimeSeries = "Naruto", ImageThumbnailUrl = "/Images/Naruto Gold Vol. 1.jpg", Price = 12.00m, ShortDescription = "Portada metalizada", LongDescription = "La edición Gold de Naruto Vol. 1 es la versión definitiva para coleccionistas del inicio de la aventura del ninja más famoso de Konoha. La portada metalizada con acabado holográfico dorado y plateado brilla espectacularmente bajo cualquier luz. Este primer volumen narra el origen de Naruto Uzumaki, el niño rechazado que sueña con convertirse en Hokage. Edición revisada con traducción mejorada y efectos de sonido en japonés transliterado. Papel couché premium que realza el arte original de Masashi Kishimoto. Incluye galería de arte exclusiva de las primeras páginas del manga. El mejor punto de entrada a la colección de Naruto.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Manga"] },
                    new AnimeProduct { Name = "Berserk Deluxe Vol. 1", AnimeSeries = "Berserk", ImageThumbnailUrl = "/Images/Berserk Deluxe Vol. 1.jpg", Price = 49.99m, ShortDescription = "Tapa dura, formato grande", LongDescription = "La edición Deluxe de Berserk en tapa dura y formato extra grande es la manera definitiva de experimentar la obra maestra de Kentaro Miura. Este primer volumen recopila los tomos 1, 2 y 3 del manga original en un impresionante libro de 672 páginas con papel de alta calidad que reproduce fielmente el extraordinario nivel artístico de Miura. El formato 18x25 cm permite apreciar cada detalle de las composiciones épicas del mangaka. La cubierta rígida con acabado mate y relieve presenta a Guts el Espadachín Negro en todo su esplendor oscuro. Incluye página de introducción por el editor. Un tributo digno al legado de Miura.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Manga"] },
                    new AnimeProduct { Name = "Chainsaw Man Vol. 1", AnimeSeries = "Chainsaw Man", ImageThumbnailUrl = "/Images/Chainsaw Man Vol. 1.jpg", Price = 9.99m, ShortDescription = "El inicio de Denji", LongDescription = "El primer volumen de Chainsaw Man presenta a Denji, un joven cazador de demonios que sobrevive miserablemente con su perro-demonio Pochita hasta que una traición lo lleva a fusionarse con él convirtiéndose en el hombre-motosierra. La obra de Tatsuki Fujimoto arrasó con todos los premios de manga en 2020 gracias a su narrativa impredecible y su arte dinámico y expresivo. Este primer volumen establece el tono oscuro, humorístico y completamente original de la serie. Papel de alta calidad con impresión nítida que captura cada línea del arte de Fujimoto. La historia más fresca y sorprendente del manga moderno japonés.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Manga"] },
                    new AnimeProduct { Name = "Spy x Family Vol. 1", AnimeSeries = "Spy x Family", ImageThumbnailUrl = "/Images/Spy x Family Vol. 1.jpg", Price = 9.99m, ShortDescription = "Misión: Formar una familia", LongDescription = "El primer volumen de Spy x Family presenta la premisa más original del manga reciente: un espía de élite que debe formar una familia falsa para completar una misión, adoptando sin saberlo a una niña telépata y casándose con una asesina secreta. La obra de Tatsuya Endo combina acción, comedia y momentos emotivos con un equilibrio perfecto que enamoró a millones de lectores mundialmente. Anya, la pequeña protagonista, se convirtió en uno de los personajes más populares del anime moderno. Este primer volumen establece los cimientos de una de las familias más disfuncionales y adorables del manga japonés contemporáneo.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Manga"] },
                    new AnimeProduct { Name = "Jujutsu Kaisen 0", AnimeSeries = "Jujutsu Kaisen", ImageThumbnailUrl = "/Images/Jujutsu Kaisen 0.png", Price = 9.99m, ShortDescription = "La precuela de Yuta Okkotsu", LongDescription = "Jujutsu Kaisen 0 es la precuela esencial que narra la historia de Yuta Okkotsu, el estudiante de primer año que porta una de las maldiciones más poderosas de la historia: el espíritu de su amiga de infancia Rika. Esta historia independiente de Gege Akutami fue la semilla de todo el universo de Jujutsu Kaisen y es fundamental para entender los eventos de la serie principal. La adaptación cinematográfica de esta historia fue un fenómeno mundial recaudando más de 100 millones de dólares. El arte más refinado de Akutami con acción de alto voltaje y momentos emotivos devastadores. Imprescindible para fans de la serie.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Manga"] },
                    new AnimeProduct { Name = "JoJo's Bizarre Adventure Part 1", AnimeSeries = "JoJo's", ImageThumbnailUrl = "/Images/JoJo's Bizarre Adventure Part 1.jpg", Price = 19.99m, ShortDescription = "Phantom Blood Vol 1", LongDescription = "El inicio de la saga más extravagante y única del manga japonés: JoJo's Bizarre Adventure Parte 1 Phantom Blood. Hirohiko Araki presenta a Jonathan Joestar, el primer JoJo, en su lucha contra Dio Brando en la Inglaterra victoriana del siglo XIX. Esta primera parte establece el universo Joestar con el poder del Hamon y los vampiros creados por la Máscara de Piedra. La edición en color premium reproduce la coloración original de Araki en todas sus páginas. La influencia de la moda italiana y el arte renacentista en el estilo de Araki es visible desde estas primeras páginas. El inicio obligatorio de una de las mejores sagas del manga mundial.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Manga"] },
                    new AnimeProduct { Name = "Akira (Edición Integral)", AnimeSeries = "Akira", ImageThumbnailUrl = "/Images/Akira (Edición Integral).jpg", Price = 35.00m, ShortDescription = "Clásico cyberpunk", LongDescription = "La edición integral de Akira reúne en un solo volumen monumental la obra cumbre del manga cyberpunk de Katsuhiro Otomo. Publicada originalmente entre 1982 y 1990, esta historia ambientada en Neo-Tokyo post-apocalíptica definió el género cyberpunk en Japón y dio origen a la película animada que revolucionó la animación mundial. El arte de Otomo es de una precisión y detalle arquitectónico sin precedentes en el manga. Esta edición de lujo en tapa dura de 360 páginas incluye páginas a color originales y comentarios del autor. Papel de alta gramaje que preserva los negros profundos del arte de Otomo. Una obra de arte literaria e histórica.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Manga"] },
                    new AnimeProduct { Name = "Dragon Ball Color Vol. 1", AnimeSeries = "Dragon Ball", ImageThumbnailUrl = "/Images/Dragon Ball Color Vol. 1.jpg", Price = 14.00m, ShortDescription = "Saga de los Saiyans a color", LongDescription = "Dragon Ball Color Vol. 1 presenta la icónica Saga de los Saiyans completamente coloreada bajo la supervisión de Shueisha, ofreciendo una experiencia de lectura completamente nueva del manga clásico de Akira Toriyama. El color añade una dimensión dramática completamente nueva a las batallas épicas entre Goku, Vegeta, Piccolo y los guerreros Saiyan. El volumen incluye la llegada de Raditz, el entrenamiento de Gohan con Piccolo y los primeros pasos hacia la batalla de Nappa y Vegeta. La coloración digital respeta el estilo original de Toriyama mientras añade profundidad y emoción visual. Papel couché brillante para máximo impacto visual en cada página.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Manga"] },
                    new AnimeProduct { Name = "Uzumaki (Junji Ito)", AnimeSeries = "Terror", ImageThumbnailUrl = "/Images/Uzumaki (Junji Ito).jpg", Price = 25.00m, ShortDescription = "Obra maestra del horror", LongDescription = "Uzumaki de Junji Ito es considerada unánimemente la obra de terror más perturbadora y artísticamente sublime del manga japonés. Esta historia narra la maldición de una ciudad japonesa obsesionada con las espirales de una manera que escala gradualmente desde lo inquietante hasta lo absolutamente aterrador. El arte de Ito alcanza cimas de detalle hipnótico que hacen que cada página sea imposible de dejar de observar a pesar del horror que transmiten. Edición integral en tapa dura que recopila los tres volúmenes originales. Papel negro de alta calidad que realza los contrastes extremos del arte de Ito. No recomendada para personas con espiral-fobia.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Manga"] },

                    // ROPA Y ACCESORIOS
                    new AnimeProduct { Name = "Capa de Akatsuki", AnimeSeries = "Naruto", ImageThumbnailUrl = "/Images/Capa de Akatsuki.jpg", Price = 45.00m, ShortDescription = "Nubes bordadas", LongDescription = "La capa oficial de la organización criminal más temida del mundo ninja: Akatsuki. Esta réplica de alta calidad está fabricada en poliéster resistente color negro con las icónicas nubes rojas bordadas a mano en toda la superficie, exactamente como aparecen en el anime de Naruto Shippuden. El cuello alto y el cierre frontal de metal reproducen fielmente el diseño original. Disponible en tallas S, M, L y XL. Lavable a máquina con colores que no destiñen. Perfecta para cosplay de Itachi, Pain, Konan, Deidara o cualquier miembro de la organización. Incluye bolsa de almacenamiento con logo de Akatsuki.", InStock = true, IsProductOfTheWeek = true, Category = Categories["Ropa y Accesorios"] },
                    new AnimeProduct { Name = "Sudadera Survey Corps", AnimeSeries = "Attack on Titan", ImageThumbnailUrl = "/Images/Sudadera Survey Corps.jpg", Price = 38.00m, ShortDescription = "Logo en la espalda", LongDescription = "Sudadera oficial del Cuerpo de Exploración de Attack on Titan, la división militar más valiente y sacrificada que lucha contra los titanes más allá de las murallas. Fabricada en algodón 80% y poliéster 20% para máxima comodidad y durabilidad. Las Alas de la Libertad bordadas en la espalda con hilo verde sobre fondo gris reproducen el emblema oficial del regimiento. El capuchón ajustable con cordón y los bolsillos frontales la hacen perfecta para el día a día. Disponible en tallas XS a XXL. Lavado a 30 grados para preservar el bordado. Incluye parche bordado pequeño del Survey Corps de regalo.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Ropa y Accesorios"] },
                    new AnimeProduct { Name = "Camiseta Capsule Corp", AnimeSeries = "Dragon Ball", ImageThumbnailUrl = "/Images/Camiseta Capsule Corp.jpg", Price = 22.00m, ShortDescription = "Algodón 100%", LongDescription = "Camiseta oficial de Capsule Corporation, la empresa de tecnología más avanzada del universo de Dragon Ball fundada por el Dr. Brief y dirigida por su hija Bulma. Fabricada en algodón 100% peinado de alta calidad, suave al tacto y resistente a múltiples lavados sin perder forma ni color. El logo de Capsule Corp está serigrafíado en alta resolución con tinta de silicona que garantiza durabilidad excepcional. Disponible en blanco, negro y azul marino en tallas XS a XXL. La misma camiseta que Vegeta usa durante su entrenamiento en la cámara del tiempo. Lavable a 40 grados. Secado rápido y antiencogimiento.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Ropa y Accesorios"] },
                    new AnimeProduct { Name = "Gorra de Jotaro", AnimeSeries = "JoJo's", ImageThumbnailUrl = "/Images/Gorra de Jotaro.jpg", Price = 18.00m, ShortDescription = "Con detalles dorados", LongDescription = "Réplica de la icónica gorra azul marino de Jotaro Kujo, el protagonista de la Parte 3 de JoJo's Bizarre Adventure. Esta gorra de visera curva está fabricada en tela de algodón pesado azul marino con el característico panel inferior negro. Los detalles dorados del símbolo de la gorra están bordados con hilo metálico que brilla bajo la luz. La visera plana y la altura de la copa reproducen exactamente el diseño extravagante que distingue a Jotaro. Ajustable mediante correa trasera de cuero para adaptarse a diferentes tallas. Perfecta para cosplay o uso casual para fans de JoJo. Yare yare daze.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Ropa y Accesorios"] },
                    new AnimeProduct { Name = "Calcetines Totoro", AnimeSeries = "Ghibli", ImageThumbnailUrl = "/Images/Calcetines Totoro.jpg", Price = 8.00m, ShortDescription = "Pack de 3 pares", LongDescription = "Pack de tres pares de calcetines oficiales de Mi Vecino Totoro del estudio Ghibli, perfectos para fans de todas las edades que quieran llevar la magia del bosque en cada paso. Cada par presenta un diseño diferente: Totoro grande gris, Totoro pequeño blanco y el Gato Bus. Fabricados en algodón 75%, poliéster 20% y elastano 5% para máxima comodidad y durabilidad. Costuras reforzadas en talón y puntera para mayor vida útil. Talla única que se adapta del 36 al 44. Lavable a máquina a 40 grados. Presentados en caja de regalo con diseño de los espíritus del bosque. El regalo perfecto para fans de Studio Ghibli.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Ropa y Accesorios"] },
                    new AnimeProduct { Name = "Mochila UA High School", AnimeSeries = "My Hero Academia", ImageThumbnailUrl = "/Images/Mochila UA High School.jpg", Price = 40.00m, ShortDescription = "Para futuros héroes", LongDescription = "Mochila oficial de la Academia UA, la mejor escuela de héroes del mundo de My Hero Academia donde estudian Deku, Bakugo, Todoroki y los futuros protectores de la sociedad. Fabricada en poliéster resistente al agua con el logo UA bordado en el panel frontal. Capacidad de 25 litros con compartimento principal, bolsillo frontal con organizador y bolsillos laterales para botella. Espalda acolchada con malla transpirable para máxima comodidad en uso prolongado. Asas acolchadas regulables y pecho con clip de seguridad. Compatible con portátil hasta 15 pulgadas. Color negro con detalles amarillo oscuro. Perfecta para estudiantes que aspiran a convertirse en los mejores héroes.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Ropa y Accesorios"] },
                    new AnimeProduct { Name = "Kimono de Zenitsu", AnimeSeries = "Demon Slayer", ImageThumbnailUrl = "/Images/Kimono de Zenitsu.jpg", Price = 35.00m, ShortDescription = "Patrón de triángulos amarillo", LongDescription = "Kimono oficial inspirado en el de Agatsuma Zenitsu, el cazador de demonios que domina el Estilo del Trueno en Demon Slayer. Fabricado en tela de poliéster de alta calidad con el característico patrón de triángulos degradados de amarillo a naranja que identifica al personaje. El corte tradicional japonés con obi incluido reproduce fielmente el vestuario del anime. Disponible en tallas S, M, L y XL para adultos. Perfecto para eventos de anime, matsuri o cosplay casual. La tela es transpirable y cómoda para uso prolongado. Lavado a mano o en bolsa de red a 30 grados. Incluye instrucciones de cómo anudar el obi correctamente.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Ropa y Accesorios"] },
                    new AnimeProduct { Name = "Llavero de Pochita", AnimeSeries = "Chainsaw Man", ImageThumbnailUrl = "/Images/Llavero de Pochita.jpg", Price = 7.00m, ShortDescription = "Peluche pequeño", LongDescription = "Adorable llavero de peluche oficial de Pochita, el perro-demonio motosierra que se convirtió en el corazón literal de Denji en Chainsaw Man. Este pequeño peluche de 8 cm reproduce fielmente la apariencia adorable de Pochita con su chainsaw en la cabeza, su pequeña nariz negra y sus ojos brillantes. Fabricado en felpa ultra suave de alta calidad con relleno de algodón hipoalergénico. El mosquetón metálico de alta resistencia soporta el peso sin deformarse. Perfecto para llaves, mochilas, bolsos o como decoración. La combinación de ternura y poder destructivo de Pochita en miniatura. El accesorio más adorable de Chainsaw Man para llevar contigo.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Ropa y Accesorios"] },
                    new AnimeProduct { Name = "Sombrero de paja de Monkey D. Luffy", AnimeSeries = "One Piece", ImageThumbnailUrl = "/Images/Sombrero de paja de Monkey D. Luffy.jpg", Price = 12.00m, ShortDescription = "Para el rey de los piratas", LongDescription = "Réplica del sombrero de paja más famoso del mundo del anime, el icónico sombrero que Shanks el Pelirrojo dio a Monkey D. Luffy cuando era niño y que se convirtió en el símbolo de su sueño de convertirse en el Rey de los Piratas. Fabricado en paja trenzada natural de alta calidad con la banda roja característica cosida a mano. El ala ancha y la copa redondeada reproducen exactamente las proporciones del sombrero original de Gol D. Roger. Talla única con banda interior ajustable. Resistente al sol y al agua. Un coleccionable que simboliza la amistad, la libertad y la aventura del Gran Viaje de One Piece.", InStock = true, IsProductOfTheWeek = false, Category = Categories["Ropa y Accesorios"] },
                    new AnimeProduct { Name = "Chaqueta de Portgas D. Ace", AnimeSeries = "One Piece", ImageThumbnailUrl = "/Images/Chaqueta de Portgas D. Ace.jpg", Price = 55.00m, ShortDescription = "Sin mangas, estilo vaquero", LongDescription = "Chaqueta oficial inspirada en el icónico estilo de Portgas D. Ace, el Comandante de la Segunda División de los Piratas Blanca Barba e hijo del Rey Pirata Gol D. Roger. Esta chaqueta de mezclilla sin mangas reproduce el look característico de Ace con el símbolo del puño ardiente bordado en la espalda. Fabricada en denim de alta calidad con desgaste deliberado en los bordes para el look rudo del personaje. Los emblemas de Whitebeard en las solapas están bordados en hilo dorado. Disponible en tallas S a XL. En memoria del personaje más querido y llorado de One Piece. Un tributo al Fuego de Ace que nunca se apagará en nuestros corazones.", InStock = false, IsProductOfTheWeek = false, Category = Categories["Ropa y Accesorios"] }
                );
                context.SaveChanges();
            }
        }

        private static Dictionary<string, Category>? categories;
        public static Dictionary<string, Category> Categories
        {
            get
            {
                if (categories == null)
                {
                    var catList = new Category[]
                    {
                        new Category { CategoryName = "Figuras", Description = "Estatuas y figuras de alta calidad" },
                        new Category { CategoryName = "Coleccionables", Description = "Réplicas, accesorios y objetos únicos" },
                        new Category { CategoryName = "Manga", Description = "Tomos físicos de tus series favoritas" },
                        new Category { CategoryName = "Ropa y Accesorios", Description = "Lleva tu estilo ninja o pirata a todos lados" }
                    };
                    categories = new Dictionary<string, Category>();
                    foreach (var cat in catList) { categories.Add(cat.CategoryName, cat); }
                }
                return categories;
            }
        }
    }
}